### ISSUE TITLE
Race condition on Application resource

### ISSUE THREAD

**Issue by miton18** [CleverCloud/terraform-provider-clevercloud#13]
I got a panic when:
Trying to declare a "clevercloud_application" resource which does not exists yet.
instance seems nil and previous error check too.

```golang
defaultFlavorName := instance.DefaultFlavor.Name
```

```
2021-12-06T17:17:13.216+0100 [WARN]  Provider "local/clevercloud/clevercloud" produced an invalid plan for clevercloud_application.poke-api, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .min_instances: planned value cty.NumberIntVal(1) for a non-computed attribute
      - .deploy_type: planned value cty.StringVal("git") for a non-computed attribute
clevercloud_application.poke-api: Creating...
2021-12-06T17:17:13.217+0100 [INFO]  Starting apply for clevercloud_application.poke-api
2021-12-06T17:17:13.217+0100 [DEBUG] clevercloud_application.poke-api: applying the planned Create change
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: PANIC: runtime error: invalid memory address or nil pointer dereference
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac7c1a]
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: 
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: goroutine 58 [running]:
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/clevercloud/terraform-provider-clevercloud/clevercloud.resourceApplicationCreate({0xd435f8, 0xc000480280}, 0xc0002037b8, {0xba66a0, 0xc00049fae0})
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/clevercloud/resource_application.go:173 +0x15a
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003a2000, {0xd435f8, 0xc000480280}, 0x2, {0xba66a0, 0xc00049fae0})
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:330 +0x12e
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003a2000, {0xd435f8, 0xc000480280}, 0xc00028a230, 0xc0002b6320, {0xba66a0, 0xc00049fae0})
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x871
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000338078, {0xd435f8, 0xc000480280}, 0xc00028e2d0)
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x9aa
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000308da0, {0xd436a0, 0xc000288000}, 0x0)
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0x6c
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc059c0, 0xc000308da0}, {0xd436a0, 0xc000288000}, 0xc000526180, 0x0)
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032c700, {0xd50290, 0xc0001f2480}, 0xc000156200, 0xc0003f27b0, 0x1221e40, 0x0)
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/google.golang.org/grpc/server.go:1194 +0xc8f
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: google.golang.org/grpc.(*Server).handleStream(0xc00032c700, {0xd50290, 0xc0001f2480}, 0xc000156200, 0x0)
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/google.golang.org/grpc/server.go:1517 +0xa2a
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/google.golang.org/grpc/server.go:859 +0x98
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-12-06T17:17:13.404+0100 [DEBUG] provider.terraform-provider-clevercloud:   /home/miton/code/go/terraform-provider-clevercloud/vendor/google.golang.org/grpc/server.go:857 +0x294
2021-12-06T17:17:13.405+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/local/clevercloud/clevercloud/0.1.0/linux_amd64/terraform-provider-clevercloud pid=3896 error="exit status 2"
2021-12-06T17:17:13.406+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-12-06T17:17:13.406+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
╷
│ Error: Plugin did not respond
│ 
│   with clevercloud_application.poke-api,
│   on poke.tf line 27, in resource "clevercloud_application" "poke-api":
│   27: resource "clevercloud_application" "poke-api" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

**Comment by gaelreyrol** [comment]
Hi @miton18,

The provider is not ready for production at all and is not even finished yet. If you wish to test it I advise you to use the `tfsdk` branch which is using the "wip" [sdk](https://github.com/hashicorp/terraform-plugin-framework) from Terraform.

But don't expect to be able to manipulate Clever Cloud resources from it without issues :wink:
